# Table Tag.
MAX_LEN_NAME_TAG = 250

MAX_LEN_COLOR_CODE_TAG = 7

MAX_LEN_NAME_SLUG = 250

# Table Ingredient.
MAX_LEN_NAME_INGREDIENT = 250

MAX_LEN_UNIT_INGREDIENT = 250

# Table Recipe.
MAX_LEN_NAME_RECIPE = 200

UPLOAD_TO_IMAGE_RECIPE = 'recipes/image/'

MIN_COOKING_TIME_IN_RECIPE = 1

MAX_COOKING_TIME_IN_RECIPE = 32_000

# Table RecipeIngredient.
MIN_AMOUNT_INGREDIENT_IN_RECIPE = 1

MAX_AMOUNT_INGREDIENT_IN_RECIPE = 32_000
